# Generated by Django 6.0.3 on 2026-06-19 15:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0008_alter_sellerpricerule_options_and_more'),
        ('orders', '0020_alter_order_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceCODBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_cod_batches_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='province_cod_batches_created', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_cod_batches_sent', to=settings.AUTH_USER_MODEL)),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='province_cod_batches', to='masterdata.shipper')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProvinceCODItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_cod', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status_before', models.CharField(blank=True, default='', max_length=30)),
                ('province_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('carrier_fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('carrier_percent_rate', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=8)),
                ('carrier_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_cod', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cod_status', models.CharField(blank=True, choices=[('SENT', 'Sent'), ('RECEIVED', 'Received'), ('PAID', 'Paid'), ('RETURNED', 'Returned')], db_index=True, default='', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('received_person', models.CharField(blank=True, default='', max_length=255)),
                ('confirmation_method', models.CharField(blank=True, choices=[('CALL', 'Phone Call'), ('TRACKING', 'Tracking'), ('CARRIER', 'Carrier Report'), ('OTHER', 'Other')], default='', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('carrier_reference', models.CharField(blank=True, default='', max_length=255)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.TextField(blank=True, default='')),
                ('seller_settled', models.BooleanField(db_index=True, default=False)),
                ('seller_settled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='provincecod.provincecodbatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='province_cod_items', to='orders.order')),
                ('paid_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_cod_paid_items', to=settings.AUTH_USER_MODEL)),
                ('received_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_cod_received_items', to=settings.AUTH_USER_MODEL)),
                ('returned_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_cod_returned_items', to=settings.AUTH_USER_MODEL)),
                ('seller_settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_cod_settled_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['cod_status', 'sent_at'], name='provincecod_cod_sta_3191ad_idx'), models.Index(fields=['seller_settled', 'cod_status'], name='provincecod_seller__42ba7e_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'order'), name='unique_province_cod_batch_order')],
            },
        ),
    ]
