# Generated by Django 6.0.3 on 2026-06-23 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_created_at'),
        ('provincecod', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincecodbatch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Province COD Batch', 'verbose_name_plural': 'Province COD Batches'},
        ),
        migrations.AlterModelOptions(
            name='provincecoditem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Province COD Item', 'verbose_name_plural': 'Province COD Items'},
        ),
        migrations.RemoveConstraint(
            model_name='provincecoditem',
            name='unique_province_cod_batch_order',
        ),
        migrations.RemoveIndex(
            model_name='provincecoditem',
            name='provincecod_cod_sta_3191ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='provincecoditem',
            name='provincecod_seller__42ba7e_idx',
        ),
        migrations.RemoveField(
            model_name='provincecodbatch',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='provincecodbatch',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='provincecodbatch',
            name='sent_by',
        ),
        migrations.AddField(
            model_name='provincecodbatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='provincecodbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='provincecodbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_province_cod_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provincecodbatch',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='provincecodbatch',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provincecodbatch',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_cod_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provincecodbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('CANCELLED', 'Cancelled'), ('DONE', 'Done')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='provincecoditem',
            name='carrier_reference',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='provincecoditem',
            name='cod_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('PAID', 'Paid'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='provincecoditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='provincecoditem',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='province_cod_item', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='provincecoditem',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provincecoditem',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='provincecoditem',
            name='carrier_fixed_fee',
        ),
        migrations.RemoveField(
            model_name='provincecoditem',
            name='carrier_percent_rate',
        ),
        migrations.RemoveField(
            model_name='provincecoditem',
            name='confirmation_method',
        ),
        migrations.RemoveField(
            model_name='provincecoditem',
            name='net_cod',
        ),
        migrations.RemoveField(
            model_name='provincecoditem',
            name='note',
        ),
        migrations.RemoveField(
            model_name='provincecoditem',
            name='paid_confirmed_by',
        ),
        migrations.RemoveField(
            model_name='provincecoditem',
            name='received_confirmed_by',
        ),
        migrations.RemoveField(
            model_name='provincecoditem',
            name='received_person',
        ),
        migrations.RemoveField(
            model_name='provincecoditem',
            name='return_reason',
        ),
        migrations.RemoveField(
            model_name='provincecoditem',
            name='returned_confirmed_by',
        ),
        migrations.RemoveField(
            model_name='provincecoditem',
            name='seller_settled_at',
        ),
        migrations.RemoveField(
            model_name='provincecoditem',
            name='seller_settled_by',
        ),
        migrations.RemoveField(
            model_name='provincecoditem',
            name='status_before',
        ),
    ]
