# Generated by Django 6.0.3 on 2026-06-23 08:22

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_alter_sellerpricerule_options_and_more'),
        ('orders', '0020_alter_order_created_at'),
        ('provincecod', '0002_alter_provincecodbatch_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincecodbatch',
            options={'ordering': ['-id'], 'verbose_name': 'Province COD Batch', 'verbose_name_plural': 'Province COD Batches'},
        ),
        migrations.AlterModelOptions(
            name='provincecoditem',
            options={'ordering': ['-id'], 'verbose_name': 'Province COD Item', 'verbose_name_plural': 'Province COD Items'},
        ),
        migrations.AddField(
            model_name='provincecodbatch',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provincecodbatch',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_cod_batches_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provincecodbatch',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_cod_batches_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provincecoditem',
            name='carrier_fixed_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='provincecoditem',
            name='carrier_percent_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='0.01 means 1 percent.', max_digits=8),
        ),
        migrations.AddField(
            model_name='provincecoditem',
            name='confirmation_method',
            field=models.CharField(blank=True, choices=[('CALL', 'Phone Call'), ('TRACKING', 'Tracking'), ('CARRIER', 'Carrier Report'), ('OTHER', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='provincecoditem',
            name='net_cod',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='provincecoditem',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='provincecoditem',
            name='paid_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_cod_paid_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provincecoditem',
            name='received_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_cod_received_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provincecoditem',
            name='received_person',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='provincecoditem',
            name='return_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='provincecoditem',
            name='returned_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_cod_returned_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provincecoditem',
            name='seller_settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provincecoditem',
            name='seller_settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_cod_settled_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provincecoditem',
            name='status_before',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='provincecodbatch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='provincecodbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_cod_batches_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provincecodbatch',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='provincecodbatch',
            name='sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='provincecodbatch',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='province_cod_batches', to='masterdata.shipper'),
        ),
        migrations.AlterField(
            model_name='provincecodbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='provincecoditem',
            name='carrier_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='provincecoditem',
            name='cod_status',
            field=models.CharField(blank=True, choices=[('SENT', 'Sent'), ('RECEIVED', 'Received'), ('PAID', 'Paid'), ('RETURNED', 'Returned')], db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='provincecoditem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='provincecoditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='province_cod_items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='provincecoditem',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='provincecoditem',
            name='sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='provincecoditem',
            index=models.Index(fields=['cod_status', 'sent_at'], name='provincecod_cod_sta_3191ad_idx'),
        ),
        migrations.AddIndex(
            model_name='provincecoditem',
            index=models.Index(fields=['seller_settled', 'cod_status'], name='provincecod_seller__42ba7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='provincecoditem',
            constraint=models.UniqueConstraint(fields=('batch', 'order'), name='unique_province_cod_batch_order'),
        ),
    ]
