# Generated by Django 6.0.3 on 2026-07-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provincecod', '0003_alter_provincecodbatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincecoditem',
            name='tracking_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
