# Generated by Django 6.0.3 on 2026-07-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provincecod', '0004_provincecoditem_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincecoditem',
            name='at_station_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='provincecoditem',
            name='delivery_issue_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='provincecoditem',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='provincecoditem',
            name='return_received_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='provincecoditem',
            name='returning_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='provincecoditem',
            name='cod_status',
            field=models.CharField(blank=True, choices=[('SENT', 'Sent'), ('AT_STATION', 'At Station'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERY_ISSUE', 'Delivery Issue'), ('RECEIVED', 'Received'), ('PAID', 'Settled from Carrier'), ('RETURNING', 'Returning'), ('RETURN_RECEIVED', 'Return Received'), ('RETURNED', 'Returned (Legacy)')], db_index=True, default='', max_length=20),
        ),
    ]
