# Generated by Django 6.0.3 on 2026-06-28 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('customerportal', '0004_sellerportalauditlog_sellerportaldailyusage_and_more'),
        ('masterdata', '0009_seller_max_portal_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_seller_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='seller_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='customerportal.sellerportalrole'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['seller', 'account_type', 'is_archived'], name='accounts_ac_seller__f6011b_idx'),
        ),
    ]
