# Generated by Django 6.0.3 on 2026-05-30 10:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0008_alter_sellerpricerule_options_and_more'),
        ('orders', '0020_alter_order_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySellerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_mode', models.CharField(choices=[('STRICT', 'Strict Stock'), ('OPTIONAL', 'Optional Stock'), ('NO_STOCK', 'No Stock / Shop Prepare')], db_index=True, default='OPTIONAL', max_length=20)),
                ('show_stock_in_portal', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_setting', to='masterdata.seller')),
            ],
            options={
                'verbose_name': 'Inventory Seller Setting',
                'verbose_name_plural': 'Inventory Seller Settings',
            },
        ),
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(blank=True, default='', help_text='Example: Serum, Cream, Gel, Shirt', max_length=80)),
                ('sku', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stock_products/')),
                ('location', models.CharField(blank=True, default='', help_text='Example: Shelf A1', max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_products', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_products', to='masterdata.seller')),
            ],
            options={
                'ordering': ['seller__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('ORDER_RESERVED', 'Order Reserved'), ('ORDER_RELEASED', 'Order Released'), ('ORDER_DELIVERED', 'Order Delivered'), ('RETURN_GOOD', 'Return Good'), ('RETURN_DAMAGED', 'Return Damaged'), ('ADJUSTMENT', 'Adjustment'), ('IMPORT_UNMATCHED', 'Import Unmatched'), ('PRODUCT_CHANGED', 'Product Changed'), ('STOCK_LACK', 'Stock Lack'), ('CONFIRM', 'Confirm Stock')], db_index=True, max_length=40)),
                ('qty_delta', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='masterdata.seller')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.stockproduct')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStockLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_product_text', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('LINKED', 'Linked'), ('UNMATCHED', 'Unmatched'), ('STOCK_LACK', 'Stock Lack'), ('NO_STOCK_REQUIRED', 'No Stock Required')], db_index=True, default='UNMATCHED', max_length=30)),
                ('shortage_qty', models.IntegerField(default=0)),
                ('reserved_qty', models.IntegerField(default=0)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_link', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_stock_links', to='masterdata.seller')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inventory_order_links', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_links', to='inventory.stockproduct')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('reserved_qty', models.IntegerField(default=0)),
                ('shortage_qty', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('LINKED', 'Linked'), ('STOCK_LACK', 'Stock Lack')], db_index=True, default='LINKED', max_length=30)),
                ('raw_product_text', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_stock_items', to='masterdata.seller')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.orderstocklink')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_stock_items', to='inventory.stockproduct')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_qty', models.IntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, default='')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='inventory.stockproduct')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_snapshots', to='masterdata.seller')),
            ],
            options={
                'ordering': ['-confirmed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_text', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_aliases', to='masterdata.seller')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='inventory.stockproduct')),
            ],
            options={
                'ordering': ['seller__name', 'alias_text'],
                'unique_together': {('seller', 'alias_text')},
            },
        ),
    ]
