# Generated by Django 6.0.3 on 2026-04-10 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_alter_seller_options_alter_shipper_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('PV', 'Province'), ('COD', 'COD')], max_length=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percent_cod', models.DecimalField(decimal_places=4, default=0, help_text='0.03 = 3%', max_digits=5)),
                ('is_locked', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='masterdata.seller')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_price_rules', to='masterdata.shipper')),
            ],
            options={
                'ordering': ['seller__name', 'shipper__name', 'rule_type'],
                'unique_together': {('seller', 'shipper', 'rule_type')},
            },
        ),
    ]
