# Generated by Django 6.0.3 on 2026-05-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_sellerpricerule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerpricerule',
            options={'ordering': ['seller__name', 'shipper__name', 'rule_type'], 'verbose_name': 'Seller Price Rule', 'verbose_name_plural': 'Seller Price Rules'},
        ),
        migrations.AlterField(
            model_name='sellerpricerule',
            name='percent_cod',
            field=models.DecimalField(decimal_places=4, default=0, help_text='0.03 = 3%. Province uses PRICE. Delivery uses COD.', max_digits=5, verbose_name='Percent Price / COD'),
        ),
        migrations.AlterField(
            model_name='sellerpricerule',
            name='rule_type',
            field=models.CharField(choices=[('PV', 'PV'), ('COD', 'COD')], help_text='PV = normal order / COD = order with COD', max_length=10),
        ),
    ]
