# Generated by Django 6.0.3 on 2026-06-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_alter_sellerpricerule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='max_portal_users',
            field=models.PositiveIntegerField(default=5, help_text='The main owner is not included in this limit.', verbose_name='Maximum Additional Portal Users'),
        ),
    ]
