# Generated by Django 6.0.2 on 2026-02-20 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverpp', '0001_initial'),
        ('masterdata', '0004_seller_created_by_shipper_created_by'),
        ('orders', '0012_rename_after_reason_bulkupdaterow_after_json_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppdeliveryitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='ppdeliverybatch',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppdeliverybatch',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.shipper'),
        ),
        migrations.AlterField(
            model_name='ppdeliverybatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pp_batches_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ppdeliveryitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order'),
        ),
    ]
