# Generated by Django 6.0.2 on 2026-02-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverpp', '0002_alter_ppdeliveryitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppdeliverybatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
