# Generated by Django 6.0.2 on 2026-02-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverpp', '0003_ppdeliverybatch_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppdeliverybatch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ppdeliveryitem',
            options={},
        ),
        migrations.AddField(
            model_name='ppdeliverybatch',
            name='return_batch_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ppdeliverybatch',
            name='shipment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ppdeliverybatch',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ppdeliveryitem',
            name='source_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ppdeliveryitem',
            name='source_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('RETURN', 'Return')], default='NORMAL', max_length=20),
        ),
    ]
