# Generated by Django 6.0.2 on 2026-02-21 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverpp', '0004_alter_ppdeliverybatch_options_and_more'),
        ('masterdata', '0004_seller_created_by_shipper_created_by'),
        ('orders', '0012_rename_after_reason_bulkupdaterow_after_json_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ppdeliveryitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ppdeliverybatch',
            name='return_batch_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ppdeliverybatch',
            name='total_pc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ppdeliverybatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ppdeliverybatch',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pp_batches', to='masterdata.shipper'),
        ),
        migrations.AlterField(
            model_name='ppdeliveryitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pp_delivery_items', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='ppdeliveryitem',
            index=models.Index(fields=['batch', 'id'], name='deliverpp_p_batch_i_788fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='ppdeliveryitem',
            index=models.Index(fields=['order'], name='deliverpp_p_order_i_b5160e_idx'),
        ),
        migrations.AddIndex(
            model_name='ppdeliveryitem',
            index=models.Index(fields=['source_type'], name='deliverpp_p_source__9ffae5_idx'),
        ),
        migrations.AddConstraint(
            model_name='ppdeliveryitem',
            constraint=models.UniqueConstraint(fields=('batch', 'order'), name='uniq_pp_batch_order'),
        ),
    ]
