# Generated by Django 6.0.2 on 2026-02-22 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverpp', '0005_alter_ppdeliveryitem_unique_together_and_more'),
        ('masterdata', '0004_seller_created_by_shipper_created_by'),
        ('orders', '0012_rename_after_reason_bulkupdaterow_after_json_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppdeliverybatch',
            options={'ordering': ['-id']},
        ),
        migrations.AddIndex(
            model_name='ppdeliverybatch',
            index=models.Index(fields=['created_at'], name='deliverpp_p_created_89d368_idx'),
        ),
        migrations.AddIndex(
            model_name='ppdeliverybatch',
            index=models.Index(fields=['status'], name='deliverpp_p_status_4013c1_idx'),
        ),
        migrations.AddIndex(
            model_name='ppdeliverybatch',
            index=models.Index(fields=['shipper'], name='deliverpp_p_shipper_7acda1_idx'),
        ),
        migrations.AddIndex(
            model_name='ppdeliveryitem',
            index=models.Index(fields=['source_code'], name='deliverpp_p_source__3a3933_idx'),
        ),
    ]
