# Generated by Django 6.0.2 on 2026-02-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverpp', '0006_alter_ppdeliverybatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppdeliverybatch',
            name='return_label_codes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
