# Generated by Django 6.0.2 on 2026-02-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverpp', '0007_ppdeliverybatch_return_label_codes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppdeliverybatch',
            old_name='return_label_codes',
            new_name='return_label_ids',
        ),
    ]
