# Generated by Django 6.0.2 on 2026-02-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverpp', '0008_rename_return_label_codes_ppdeliverybatch_return_label_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppdeliverybatch',
            old_name='return_label_ids',
            new_name='return_label_codes',
        ),
    ]
