# Generated by Django 6.0.2 on 2026-02-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverpp', '0009_rename_return_label_ids_ppdeliverybatch_return_label_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppdeliverybatch',
            name='return_batch_ids',
        ),
    ]
