# Generated by Django 6.0.2 on 2026-02-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverpp', '0010_remove_ppdeliverybatch_return_batch_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppdeliverybatch',
            name='return_batch_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
