# Generated by Django 6.0.2 on 2026-02-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverpp', '0011_ppdeliverybatch_return_batch_ids'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ppdeliveryitem',
            name='deliverpp_p_source__3a3933_idx',
        ),
        migrations.AddField(
            model_name='ppdeliverybatch',
            name='return_pc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ppdeliverybatch',
            name='shipment_pc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ppdeliveryitem',
            name='source_type',
            field=models.CharField(choices=[('NORMAL', 'Normal')], default='NORMAL', max_length=20),
        ),
        migrations.RemoveField(
            model_name='ppdeliveryitem',
            name='source_code',
        ),
    ]
