# Generated by Django 6.0.2 on 2026-02-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverpp', '0012_remove_ppdeliveryitem_deliverpp_p_source__3a3933_idx_and_more'),
        ('orders', '0012_rename_after_reason_bulkupdaterow_after_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppdeliverybatch',
            name='return_pc',
        ),
        migrations.RemoveField(
            model_name='ppdeliverybatch',
            name='shipment_pc',
        ),
        migrations.AddField(
            model_name='ppdeliveryitem',
            name='source_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ppdeliveryitem',
            name='source_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('RETURN', 'Return')], default='NORMAL', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ppdeliveryitem',
            index=models.Index(fields=['source_code'], name='deliverpp_p_source__3a3933_idx'),
        ),
    ]
