# Generated by Django 6.0.2 on 2026-02-26 08:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverpp', '0013_remove_ppdeliverybatch_return_pc_and_more'),
        ('masterdata', '0004_seller_created_by_shipper_created_by'),
        ('orders', '0013_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppdeliveryitem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveConstraint(
            model_name='ppdeliveryitem',
            name='uniq_pp_batch_order',
        ),
        migrations.RemoveIndex(
            model_name='ppdeliverybatch',
            name='deliverpp_p_created_89d368_idx',
        ),
        migrations.RemoveIndex(
            model_name='ppdeliverybatch',
            name='deliverpp_p_status_4013c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='ppdeliverybatch',
            name='deliverpp_p_shipper_7acda1_idx',
        ),
        migrations.RemoveIndex(
            model_name='ppdeliveryitem',
            name='deliverpp_p_batch_i_788fd0_idx',
        ),
        migrations.RemoveIndex(
            model_name='ppdeliveryitem',
            name='deliverpp_p_order_i_b5160e_idx',
        ),
        migrations.RemoveIndex(
            model_name='ppdeliveryitem',
            name='deliverpp_p_source__9ffae5_idx',
        ),
        migrations.AlterField(
            model_name='ppdeliverybatch',
            name='assigned_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='ppdeliverybatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pp_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ppdeliverybatch',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ppdeliverybatch',
            name='return_batch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ppdeliverybatch',
            name='shipment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ppdeliverybatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='ppdeliverybatch',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ppdeliverybatch',
            name='total_pc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ppdeliveryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ppdeliveryitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pp_items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='ppdeliveryitem',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ppdeliveryitem',
            name='source_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ppdeliveryitem',
            name='source_type',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('RETURN', 'RETURN')], default='NORMAL', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='ppdeliveryitem',
            unique_together={('batch', 'order')},
        ),
        migrations.AddIndex(
            model_name='ppdeliverybatch',
            index=models.Index(fields=['status', 'created_at'], name='deliverpp_p_status_e52bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='ppdeliveryitem',
            index=models.Index(fields=['batch', 'source_type'], name='deliverpp_p_batch_i_2c9af7_idx'),
        ),
    ]
