# Generated by Django 6.0.2 on 2026-02-28 03:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverpp', '0014_alter_ppdeliveryitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_khr_rate', models.PositiveIntegerField(default=4100)),
                ('balance_tolerance_khr', models.PositiveIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AddField(
            model_name='ppdeliveryitem',
            name='cod_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppdeliveryitem',
            name='delivery_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppdeliveryitem',
            name='ticked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ppdeliverybatch',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppdeliverybatch',
            name='return_batch_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ppdeliverybatch',
            name='shipment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ppdeliverybatch',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ppdeliverybatch',
            name='total_pc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ClearPPCOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('cash_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cash_khr', models.PositiveIntegerField(default=0)),
                ('aba_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('aba_khr', models.PositiveIntegerField(default=0)),
                ('expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('target_total_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('input_total_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('diff_khr', models.IntegerField(default=0)),
                ('is_balanced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clear_cod', to='deliverpp.ppdeliverybatch')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
