# Generated by Django 6.0.2 on 2026-02-28 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverpp', '0015_systemsetting_ppdeliveryitem_cod_cleared_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={},
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverpp_settings_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='balance_tolerance_khr',
            field=models.PositiveIntegerField(default=99),
        ),
    ]
