# Generated by Django 6.0.2 on 2026-02-28 08:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverpp', '0016_alter_systemsetting_options_systemsetting_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppdeliveryitem',
            name='cod_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='ppdeliveryitem',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ppdeliveryitem',
            name='tick_locked',
            field=models.BooleanField(default=False),
        ),
    ]
