# Generated by Django 6.0.3 on 2026-08-19 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverpp', '0017_ppdeliveryitem_cod_snapshot_ppdeliveryitem_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ppdeliveryitem',
            name='inbound_scanned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='ppdeliveryitem',
            name='inbound_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppdeliveryitem',
            name='inbound_scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_inbound_scans', to=settings.AUTH_USER_MODEL),
        ),
    ]
