# Generated by Django 6.0.2 on 2026-03-08 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0004_seller_created_by_shipper_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('report_date', models.DateField(db_index=True)),
                ('done_count', models.PositiveIntegerField(default=0)),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('total_cod', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('png_path', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('WAITING_CHECK', 'WAITING_CHECK'), ('APPROVED', 'APPROVED'), ('NEED_FIX', 'NEED_FIX'), ('HOLD', 'HOLD'), ('TRANSFERRED', 'TRANSFERRED'), ('SENT_TO_CUSTOMER', 'SENT_TO_CUSTOMER')], db_index=True, default='WAITING_CHECK', max_length=30)),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=100)),
                ('telegram_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reaction_emoji', models.CharField(blank=True, default='', max_length=20)),
                ('telegram_actor_id', models.CharField(blank=True, default='', max_length=100)),
                ('telegram_actor_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_daily_reports', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='masterdata.seller')),
            ],
            options={
                'ordering': ['-report_date', 'shop__name', '-id'],
                'unique_together': {('shop', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='ShopDailyReportStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, default='', max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('emoji', models.CharField(blank=True, default='', max_length=20)),
                ('actor_name', models.CharField(blank=True, default='', max_length=255)),
                ('actor_telegram_id', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='reportbot.shopdailyreport')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
