# Generated by Django 6.0.2 on 2026-02-15 12:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0012_rename_after_reason_bulkupdaterow_after_json_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnShopBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnShopBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_before', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status_before', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returnshop.returnshopbatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
            ],
            options={
                'unique_together': {('batch', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ReturnShopLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ship_to_address', models.TextField(blank=True, default='')),
                ('ship_to_phone', models.CharField(blank=True, default='', max_length=50)),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='returnshop.returnshopbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnShopLabelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='returnshop.returnshopbatchitem')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_items', to='returnshop.returnshoplabel')),
            ],
            options={
                'unique_together': {('label', 'batch_item')},
            },
        ),
    ]
