# Generated by Django 6.0.2 on 2026-02-19 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_after_reason_bulkupdaterow_after_json_and_more'),
        ('returnshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnshopbatch',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='returnshopbatchitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='returnshoplabel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='returnshoplabelitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='returnshopbatchitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='returnshoplabelitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='returnshoplabel',
            name='mode',
            field=models.CharField(choices=[('MERGE', 'MERGE'), ('SHOP', 'SHOP')], default='MERGE', max_length=10),
        ),
        migrations.AddField(
            model_name='returnshoplabel',
            name='shop_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='returnshoplabelitem',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnshopbatch',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnshopbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='returnshopbatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returnshop_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='returnshopbatch',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='returnshopbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnshopbatchitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='returnshopbatchitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returnshop_batch_items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='returnshopbatchitem',
            name='status_before',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='returnshoplabel',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='returnshoplabel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='returnshoplabel',
            name='ship_to_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='returnshoplabelitem',
            name='batch_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='label_items', to='returnshop.returnshopbatchitem'),
        ),
        migrations.AlterField(
            model_name='returnshoplabelitem',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returnshop.returnshoplabel'),
        ),
        migrations.AddIndex(
            model_name='returnshopbatch',
            index=models.Index(fields=['status', 'assigned_at'], name='returnshop__status_57480d_idx'),
        ),
        migrations.AddIndex(
            model_name='returnshopbatch',
            index=models.Index(fields=['created_at'], name='returnshop__created_01fe6c_idx'),
        ),
        migrations.AddIndex(
            model_name='returnshopbatchitem',
            index=models.Index(fields=['batch', 'id'], name='returnshop__batch_i_b2a28e_idx'),
        ),
        migrations.AddIndex(
            model_name='returnshopbatchitem',
            index=models.Index(fields=['order'], name='returnshop__order_i_f1c603_idx'),
        ),
        migrations.AddIndex(
            model_name='returnshoplabel',
            index=models.Index(fields=['batch', 'created_at'], name='returnshop__batch_i_c271ca_idx'),
        ),
        migrations.AddIndex(
            model_name='returnshoplabel',
            index=models.Index(fields=['mode'], name='returnshop__mode_4c428f_idx'),
        ),
        migrations.AddIndex(
            model_name='returnshoplabel',
            index=models.Index(fields=['code'], name='returnshop__code_930a64_idx'),
        ),
        migrations.AddIndex(
            model_name='returnshoplabelitem',
            index=models.Index(fields=['label'], name='returnshop__label_i_f8b9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='returnshoplabelitem',
            index=models.Index(fields=['batch_item'], name='returnshop__batch_i_cef7df_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnshopbatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'order'), name='uniq_rts_batch_order'),
        ),
        migrations.AddConstraint(
            model_name='returnshoplabelitem',
            constraint=models.UniqueConstraint(fields=('label', 'batch_item'), name='uniq_rts_label_batchitem'),
        ),
    ]
