# Generated by Django 6.0.2 on 2026-02-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinceops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincebatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
