# Generated by Django 6.0.2 on 2026-02-14 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinceops', '0002_alter_provincebatch_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provincebatch',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='province_batches_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provincebatch',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provincebatch',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='province_batches_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provincebatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
