# Generated by Django 6.0.2 on 2026-02-14 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinceops', '0003_provincebatch_assigned_by_provincebatch_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincebatchitem',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='provincebatchitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='provincebatchitem',
            name='prev_cod',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='provincebatchitem',
            name='prev_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
