# Generated by Django 6.0.2 on 2026-02-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provinceops', '0004_alter_provincebatchitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincebatchitem',
            options={},
        ),
        migrations.RenameField(
            model_name='provincebatchitem',
            old_name='prev_cod',
            new_name='cod_before',
        ),
        migrations.RenameField(
            model_name='provincebatchitem',
            old_name='prev_status',
            new_name='status_before',
        ),
        migrations.RemoveField(
            model_name='provincebatch',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='provincebatch',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='provincebatch',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='provincebatchitem',
            name='created_at',
        ),
    ]
