# Generated by Django 6.0.2 on 2026-02-15 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinceops', '0005_alter_provincebatchitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincebatchitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
