# Generated by Django 6.0.1 on 2026-02-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
