# Generated by Django 6.0.1 on 2026-02-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_seller_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_khr', models.DecimalField(decimal_places=2, default=4100, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
