# Generated by Django 6.0.1 on 2026-02-07 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_seller_address_seller_phone_shipper_phone_and_more'),
        ('orders', '0003_ordersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.importbatch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='masterdata.seller'),
        ),
    ]
