# Generated by Django 6.0.1 on 2026-02-07 05:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_import_batch_alter_order_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importbatch',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ordersetting',
            options={'verbose_name': 'Order Setting', 'verbose_name_plural': 'Order Settings'},
        ),
        migrations.AlterField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('OUT_FOR_DELIVERY', 'OUT_FOR_DELIVERY'), ('DELIVERED', 'DELIVERED'), ('PROVINCE_ASSIGNED', 'PROVINCE_ASSIGNED'), ('RETURN_ASSIGNED', 'RETURN_ASSIGNED'), ('VOID', 'VOID')], db_index=True, default='CREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ordersetting',
            name='usd_to_khr',
            field=models.DecimalField(decimal_places=2, default=Decimal('4100'), help_text='Exchange rate: 1 USD = ? KHR', max_digits=12),
        ),
    ]
