# Generated by Django 6.0.1 on 2026-02-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_importbatch_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='print_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
