# Generated by Django 6.0.1 on 2026-02-08 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_print_count_order_seller_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUpdateBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BulkUpdateRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='', max_length=30)),
                ('cod', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('province_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='orders.bulkupdatebatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_update_rows', to='orders.order')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
