# Generated by Django 6.0.1 on 2026-02-09 16:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_after_additional_fee_bulkupdaterow_additional_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkupdaterow',
            name='status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='tracking_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bulkupdaterow',
            name='after_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulkupdaterow',
            name='before_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordersetting',
            name='usd_to_khr',
            field=models.DecimalField(decimal_places=2, default=Decimal('4100'), max_digits=12),
        ),
    ]
