# Generated by Django 6.0.1 on 2026-02-10 02:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_bulkupdaterow_status_bulkupdaterow_tracking_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkupdaterow',
            old_name='additional_fee',
            new_name='after_additional_fee',
        ),
        migrations.RenameField(
            model_name='bulkupdaterow',
            old_name='cod',
            new_name='after_cod',
        ),
        migrations.RenameField(
            model_name='bulkupdaterow',
            old_name='delivery_fee',
            new_name='after_delivery_fee',
        ),
        migrations.RenameField(
            model_name='bulkupdaterow',
            old_name='province_fee',
            new_name='after_price',
        ),
        migrations.RenameField(
            model_name='bulkupdaterow',
            old_name='reason',
            new_name='after_reason',
        ),
        migrations.RenameField(
            model_name='bulkupdaterow',
            old_name='remark',
            new_name='after_receiver_address',
        ),
        migrations.RemoveField(
            model_name='bulkupdaterow',
            name='after_json',
        ),
        migrations.RemoveField(
            model_name='bulkupdaterow',
            name='before_json',
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='after_product_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='after_province_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='after_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='after_receiver_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='after_receiver_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='after_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='after_seller_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='after_seller_order_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='before_additional_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='before_cod',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='before_delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='before_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='before_product_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='before_province_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='before_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='before_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='before_receiver_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='before_receiver_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='before_receiver_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='before_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='before_seller_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bulkupdaterow',
            name='before_seller_order_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordersetting',
            name='usd_to_khr',
            field=models.DecimalField(decimal_places=2, default=Decimal('4100'), help_text='Exchange rate: 1 USD = ? KHR', max_digits=12),
        ),
    ]
