# Generated by Django 6.0.2 on 2026-02-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_after_reason_bulkupdaterow_after_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('OUT_FOR_DELIVERY', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('PROVINCE_ASSIGNED', 'PROVINCE_ASSIGNED'), ('RETURN_ASSIGNED', 'RETURN_ASSIGNED'), ('VOID', 'VOID')], db_index=True, default='CREATED', max_length=30),
        ),
    ]
