# Generated by Django 6.0.2 on 2026-03-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('INBOUND', 'INBOUND'), ('OUT_FOR_DELIVERY', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('PROVINCE_ASSIGNED', 'PROVINCE_ASSIGNED'), ('RETURN_ASSIGNED', 'RETURN_ASSIGNED'), ('VOID', 'VOID')], db_index=True, default='CREATED', max_length=30),
        ),
    ]
