# Generated by Django 6.0.2 on 2026-03-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clear_delivery',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='done_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
