# Generated by Django 6.0.3 on 2026-03-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_updated_at_order_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('INBOUND', 'INBOUND'), ('OUT_FOR_DELIVERY', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('RETURNED', 'RETURNED'), ('PROVINCE_ASSIGNED', 'PROVINCE_ASSIGNED'), ('RETURN_ASSIGNED', 'RETURN_ASSIGNED'), ('VOID', 'VOID')], db_index=True, default='CREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderactivity',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('inbound', 'Inbound'), ('assign', 'Assign'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('return_assigned', 'Return Assigned'), ('void', 'Void'), ('delete', 'Delete'), ('restore', 'Restore'), ('lock', 'Lock'), ('unlock', 'Unlock'), ('print', 'Print')], max_length=50),
        ),
    ]
