# Generated by Django 6.0.3 on 2026-03-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_status_alter_orderactivity_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('INBOUND', 'INBOUND'), ('OUT_FOR_DELIVERY', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('RETURNING', 'RETURNING'), ('RETURNED', 'RETURNED'), ('PROVINCE_ASSIGNED', 'PROVINCE_ASSIGNED'), ('RETURN_ASSIGNED', 'RETURN_ASSIGNED'), ('VOID', 'VOID')], db_index=True, default='CREATED', max_length=30),
        ),
    ]
