# Generated by Django 6.0.3 on 2026-03-10 17:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0005_seller_portal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_phone', models.CharField(max_length=50)),
                ('sender_address', models.TextField()),
                ('total_pc', models.IntegerField(default=1)),
                ('remark', models.TextField(blank=True)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.CharField(max_length=50)),
                ('arrive_date', models.DateField()),
                ('arrive_time', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100)),
                ('telegram_message_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.seller')),
            ],
        ),
    ]
