# Generated by Django 6.0.3 on 2026-03-18 14:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0002_sellerbooking_processed_at_and_more'),
        ('masterdata', '0005_seller_portal_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPortalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.CharField(blank=True, default='', max_length=100)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_sessions', to='masterdata.seller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_portal_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_at'],
            },
        ),
    ]
