# Generated by Django 6.0.3 on 2026-06-28 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0003_sellerportalsession'),
        ('masterdata', '0009_seller_max_portal_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPortalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerPortalDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('active_seconds', models.PositiveBigIntegerField(default=0)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-usage_date', 'seller__name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='SellerPortalPageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(max_length=150)),
                ('page_name', models.CharField(blank=True, default='', max_length=180)),
                ('active_seconds', models.PositiveBigIntegerField(default=0)),
                ('page_views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-active_seconds', 'page_name'],
            },
        ),
        migrations.CreateModel(
            name='SellerPortalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['seller__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sellerportalsession',
            name='active_seconds',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerportalsession',
            name='last_page_key',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='sellerportalsession',
            name='last_page_name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddIndex(
            model_name='sellerportalsession',
            index=models.Index(fields=['seller', 'user', 'logout_at'], name='customerpor_seller__5860dd_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerportalsession',
            index=models.Index(fields=['seller', 'last_activity_at'], name='customerpor_seller__a62b69_idx'),
        ),
        migrations.AddField(
            model_name='sellerportalauditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_portal_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerportalauditlog',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_audit_logs', to='masterdata.seller'),
        ),
        migrations.AddField(
            model_name='sellerportalauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_portal_target_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerportaldailyusage',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_daily_usage', to='masterdata.seller'),
        ),
        migrations.AddField(
            model_name='sellerportaldailyusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_portal_daily_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerportalpageusage',
            name='daily_usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='customerportal.sellerportaldailyusage'),
        ),
        migrations.AddField(
            model_name='sellerportalrole',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_roles', to='masterdata.seller'),
        ),
        migrations.AddIndex(
            model_name='sellerportalauditlog',
            index=models.Index(fields=['seller', 'created_at'], name='customerpor_seller__3950fb_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerportalauditlog',
            index=models.Index(fields=['action', 'created_at'], name='customerpor_action_1285fb_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerportaldailyusage',
            index=models.Index(fields=['seller', 'usage_date'], name='customerpor_seller__cf4e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerportaldailyusage',
            index=models.Index(fields=['user', 'usage_date'], name='customerpor_user_id_8d8b3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellerportaldailyusage',
            constraint=models.UniqueConstraint(fields=('seller', 'user', 'usage_date'), name='unique_seller_user_daily_usage'),
        ),
        migrations.AddConstraint(
            model_name='sellerportalpageusage',
            constraint=models.UniqueConstraint(fields=('daily_usage', 'page_key'), name='unique_daily_portal_page_usage'),
        ),
        migrations.AddConstraint(
            model_name='sellerportalrole',
            constraint=models.UniqueConstraint(fields=('seller', 'name'), name='unique_seller_portal_role_name'),
        ),
    ]
