# Generated by Django 6.0.3 on 2026-07-04 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0004_sellerportalauditlog_sellerportaldailyusage_and_more'),
        ('masterdata', '0009_seller_max_portal_users'),
        ('orders', '0020_alter_order_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='seller_order_uploads/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IMPORTED', 'Imported')], db_index=True, default='PENDING', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_seller_uploads', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_seller_uploads', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to='masterdata.seller')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_order_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SellerUploadRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('seller_order_code', models.CharField(blank=True, default='', max_length=100)),
                ('receiver_name', models.CharField(blank=True, default='', max_length=200)),
                ('receiver_phone', models.CharField(blank=True, default='', max_length=50)),
                ('receiver_address', models.TextField(blank=True, default='')),
                ('product_desc', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cod', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remark', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('ERROR', 'Error'), ('DUPLICATE', 'Duplicate')], db_index=True, default='VALID', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='customerportal.selleruploadbatch')),
                ('imported_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_upload_rows', to='orders.order')),
            ],
            options={
                'ordering': ['row_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='selleruploadbatch',
            index=models.Index(fields=['seller', 'status', 'created_at'], name='customerpor_seller__77b119_idx'),
        ),
        migrations.AddIndex(
            model_name='selleruploadbatch',
            index=models.Index(fields=['status', 'created_at'], name='customerpor_status_11199c_idx'),
        ),
        migrations.AddIndex(
            model_name='selleruploadrow',
            index=models.Index(fields=['batch', 'status'], name='customerpor_batch_i_326baf_idx'),
        ),
        migrations.AddIndex(
            model_name='selleruploadrow',
            index=models.Index(fields=['seller_order_code'], name='customerpor_seller__f5aaa6_idx'),
        ),
        migrations.AddConstraint(
            model_name='selleruploadrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_seller_upload_batch_row_number'),
        ),
    ]
