# Generated by Django 6.0.3 on 2026-07-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0005_selleruploadbatch_selleruploadrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleruploadrow',
            name='seller_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
