# Generated by Django 6.0.3 on 2026-07-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0006_selleruploadrow_seller_name'),
        ('orders', '0020_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleruploadbatch',
            name='upload_remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='selleruploadrow',
            name='matched_product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='selleruploadrow',
            name='matched_sku',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='selleruploadrow',
            name='product_name_input',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='selleruploadrow',
            name='sku_input',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='selleruploadrow',
            index=models.Index(fields=['sku_input'], name='customerpor_sku_inp_710e09_idx'),
        ),
        migrations.AddIndex(
            model_name='selleruploadrow',
            index=models.Index(fields=['matched_sku'], name='customerpor_matched_2a2656_idx'),
        ),
    ]
